apiVersion: v1
kind: Service
metadata:
  name: quickstart-hive-metastore
  labels:
{{ include "impala.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: thrift
      port: 9083
      targetPort: thrift
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "impala.name" . }}
    app.kubernetes.io/component: hms
