apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "impala.fullname" . }}-impalad
  labels:
{{ include "impala.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "impala.name" . }}
      app.kubernetes.io/component: impalad
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ include "impala.name" . }}
        app.kubernetes.io/component: impalad
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      containers:
        - name: impalad
          image: {{ include "impala.image" (dict "Values" .Values "imageName" "impalad_coord_exec") }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -v=1
            - -redirect_stdout_stderr=false
            - -logtostderr
            - -state_store_host={{ .Values.statestore.host | default (printf "%s-statestored" (include "impala.fullname" .)) }}
            - -catalog_service_host={{ .Values.catalog.host | default (printf "%s-catalogd" (include "impala.fullname" .)) }}
{{- if .Values.impalad.kuduMasterHosts }}
            - -kudu_master_hosts={{ .Values.impalad.kuduMasterHosts }}
{{- end }}
            - -mt_dop_auto_fallback={{ .Values.impalad.mtDopAutoFallback | default true }}
            - -default_query_options={{ .Values.impalad.defaultQueryOptions }}
            - -mem_limit={{ .Values.impalad.memLimit }}
{{- range .Values.impalad.extraArgs }}
            - {{ . | quote }}
{{- end }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.impalad.javaToolOptions | quote }}
          ports:
            - name: beeswax
              containerPort: 21000
            - name: hs2
              containerPort: 21050
            - name: web
              containerPort: 25000
            - name: hs2-http
              containerPort: 28000
          volumeMounts:
            - name: warehouse
              mountPath: /user/hive/warehouse
            - name: conf
              mountPath: /opt/impala/conf/hive-site.xml
              subPath: hive-site.xml
      volumes:
        - name: conf
          configMap:
            name: {{ include "impala.fullname" . }}-conf
        - name: warehouse
{{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "impala.fullname" . }}-warehouse
{{- else }}
          emptyDir: {}
{{- end }}
